import { CreateDesignParams, Design, DesignGuideline, DesignView } from "@/types/designs";
import { createClientbyRole } from "@/utils/adminHelper";
import { createClient } from "@/utils/supabase/ssr_client/server";


/**
 * Creates a new design instance for a specific store.
 * The Design_Id is now generated by the database by default.
 */
export async function createDesign({
	designId,
	designGuideline,
	designName,
	imageUrl,
	storeCode,
	height = 7,
	width = 7,
}: CreateDesignParams): Promise<Design[]> {
	const supabase = await createClient();
	const {
		data: { user },
	} = await supabase.auth.getUser();

	if (!user) {
		throw new Error("User not authenticated to create a design.");
	}

	const { data, error } = await supabase
		.from("designs")
		.insert([
			{
				Design_Id: designId,
				Design_Guideline: designGuideline,
				Image_URL: imageUrl,
				Design_Name: designName,
				user_id: user.id,
				store_code: storeCode,
				height,
				width,
			},
		])
		.select()

	if (error) {
		throw new Error(`Failed to create design: ${error.message}`);
	}

	return data || [];
}

export async function updateDesign(
	design_id: number,
	designUpdateParams: Partial<Design>
): Promise<Design[]> {
	const { supabase, isAdmin, user_id } = await createClientbyRole();
	
	let query = supabase
		.from("designs")
		.update(designUpdateParams)
		.eq("Design_Id", design_id)
	
	if (!isAdmin) {
			query = query.eq("user_id", user_id);
		}

	const { data, error } = await query.select();

	console.log("Updated data: ", data, "Error", error)

	if (error) {
		throw new Error(`Failed to update design: ${error.message}`);
	}

	return data || [];
}

/**
 * Deletes a design by its ID, ensuring the user has the correct permissions.
 * @param design_id The ID of the design to delete.
 */
export async function deleteDesign(design_id: string): Promise<void> {
	const { supabase, isAdmin, user_id } = await createClientbyRole();

	let query = supabase
		.from("designs")
		.delete()
		.eq("Design_Id", design_id);

	if (!isAdmin) {
		query = query.eq("user_id", user_id);
	}

	const { data, error } = await query;

	if (error) {
		throw new Error(`Failed to delete design: ${error.message}`);
	}

	console.log("Design deleted successfully : ",data);
}

/**
 * Fetches all available design guidelines from the 'design_guidelines' table.
 */
export async function getDesignGuidelines(): Promise<DesignGuideline[]> {
	const supabase = await createClient();
	const { data, error } = await supabase
		.from("design_guidelines")
		.select("*")

	if (error) {
		throw new Error(`Failed to fetch design guidelines: ${error.message}`);
	}

	return data || [];
}


export async function getExistingDesigns(storeCode: string): Promise<DesignView[]> {
	const supabase = await createClient();

	const {data: session} = await supabase.auth.getSession();

	if (!session) {
		throw new Error("User not authenticated to fetch designs.");
	}

	const { data, error } = await supabase
		.from("v_designs")
		.select("*")
		.eq("store_code", storeCode);

	if (error) {
		throw new Error(`Failed to fetch existing designs: ${error.message}`);
	}

	console.log(`Fetched Existing Designs in Store ${storeCode} : `, data)

	return data || [];
}
